
device_id: cuda:0
mode: train
apr_checkpoint_path: null
dataset:
  dataset_path: F:\CambridgeLandmarks\ShopFacade
  labels_file: F:\CambridgeLandmarks\ShopFacade\GT_ShopFacade_train.csv_with_cluster_idx_poses_10.csv
  transform: train_baseline
  resi_pose: 0
train_params:
  n_epochs: 350
  lr: 0.001
  weight_decay: 0.0000001
  lr_scheduler_step_size: 50
  lr_scheduler_gamma: 0.1
  batch_size: 16
  num_workers: 4
  n_freq_print: 5
  n_freq_checkpoint: 50
  pose_loss_params:
    learnable : True
    s_x: -3.0
    s_q: -6.5
    norm: 2
apr_params:
  encoder_name: eigenplaces
  mlp_dim: 1024
  eigenplaces:
    backbone: ResNet50
    output_dim: 2048
  imagenet:
    backbone: resnet50
    output_dim: 2048
  orientation_representation: quat
  dropout: 0.1
  num_clusters: 10




